export enum ErrorCode {
  SERVER_ERROR = 'SERVER_ERROR',
  FORBIDDEN = 'FORBIDDEN',
  NOT_FOUND = 'NOT_FOUND',
  INVALID_TOKEN = 'INVALID_TOKEN',
  EXPIRED_TOKEN = 'EXPIRED_TOKEN',
  TOKEN_NOT_FOUND = 'TOKEN_NOT_FOUND',
  ALREADY_EXIST = 'ALREADY_EXIST',
  MISSION_TOO_SHORT_CONTENT = 'MISSION_TOO_SHORT_CONTENT',
}
