export enum RoomErrorCode {
  NOT_FOUND = 'ROOM.NOT_FOUND',
  BAD_ROOMCODE = 'ROOM.BAD_ROOMCODE',
}

export enum ErrorCode {
  SERVER_ERROR = 'SERVER_ERROR',
  INVALID_TOKEN = 'INVALID_TOKEN',
  EXPIRED_TOKEN = 'EXPIRED_TOKEN',
}
