export enum ErrorCode {
  SERVER_ERROR = 'SERVER_ERROR',
  INVALID_TOKEN = 'INVALID_TOKEN',
  EXPIRED_TOKEN = 'EXPIRED_TOKEN',
  TOKEN_NOT_FOUND = 'TOKEN_NOT_FOUND',
  ROOM_NOT_FOUND = 'ROOM_NOT_FOUND',
  ALREADY_EXIST = 'ALREADY_EXIST',
}
